// stores/videoDetailsData.js

export const videoDetailsMap = {
  "1": {
    id: "1",
    title: "Amazing Tutorial: Master React in 30 Minutes",
    channel: "Code Masters",
    views: "2.3M views",
    duration: "30:45",
    description: "Learn React from scratch in this comprehensive 30-minute tutorial. Perfect for beginners!",
    channelSubscribers: "1.2M subscribers",
    uploadDate: "2 days ago",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
  },
  "2": {
    id: "2",
    title: "Top 10 Web Development Trends 2024",
    channel: "Tech Insights",
    views: "1.8M views",
    duration: "15:20",
    description: "Discover the latest web development trends that will dominate 2024.",
    channelSubscribers: "850K subscribers",
    uploadDate: "1 week ago",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
  },
  "3": {
    id: "3",
    title: "Building Modern UI with Tailwind CSS",
    channel: "Design Pro",
    views: "890K views",
    duration: "22:15",
    description: "Master Tailwind CSS and build beautiful, responsive user interfaces.",
    channelSubscribers: "650K subscribers",
    uploadDate: "3 days ago",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
  },
  "4": {
    id: "4",
    title: "JavaScript Tips Every Developer Should Know",
    channel: "Code Academy",
    views: "1.2M views",
    duration: "18:30",
    description: "Essential JavaScript tips and tricks that will make you a better developer.",
    channelSubscribers: "2M subscribers",
    uploadDate: "5 days ago",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
  },
  "5": {
    id: "5",
    title: "The Future of Frontend Development",
    channel: "Tech Talks",
    views: "650K views",
    duration: "25:10",
    description: "An in-depth look at where frontend development is heading in the next few years.",
    channelSubscribers: "500K subscribers",
    uploadDate: "1 week ago",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
  },
  "t1": {
    id: "t1",
    title: "Viral Tech Unboxing",
    channel: "Tech Review",
    views: "5.2M views",
    duration: "12:30",
    description: "Unboxing the latest viral tech gadget that everyone is talking about!",
    channelSubscribers: "3.5M subscribers",
    uploadDate: "1 day ago",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
  },
  "t2": {
    id: "t2",
    title: "Breaking Tech News Today",
    channel: "News Daily",
    views: "3.1M views",
    duration: "8:45",
    description: "Stay updated with the latest breaking news in the tech world.",
    channelSubscribers: "5M subscribers",
    uploadDate: "6 hours ago",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
  },
  "t3": {
    id: "t3",
    title: "Mind-Blowing AI Demo",
    channel: "AI World",
    views: "4.8M views",
    duration: "15:20",
    description: "Watch this incredible demonstration of cutting-edge AI technology.",
    channelSubscribers: "2.8M subscribers",
    uploadDate: "2 days ago",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
  },
  "m1": {
    id: "m1",
    title: "Coding Music Mix 2024",
    channel: "Focus Beats",
    views: "12M views",
    duration: "2:30:00",
    description: "The perfect music mix to help you focus while coding. 2.5 hours of pure concentration.",
    channelSubscribers: "8M subscribers",
    uploadDate: "1 month ago",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
  },
  "m2": {
    id: "m2",
    title: "Lofi Hip Hop Study Session",
    channel: "Chill Vibes",
    views: "8.5M views",
    duration: "1:45:30",
    description: "Relax and study with this lofi hip hop mix. Perfect background music for productivity.",
    channelSubscribers: "6M subscribers",
    uploadDate: "2 weeks ago",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
  },
  "m3": {
    id: "m3",
    title: "Electronic Programming Playlist",
    channel: "Beat Masters",
    views: "6.2M views",
    duration: "1:20:15",
    description: "Electronic beats to keep you energized while programming.",
    channelSubscribers: "4M subscribers",
    uploadDate: "1 week ago",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4",
  },
  "g1": {
    id: "g1",
    title: "New Game Release Review",
    channel: "Gaming Pro",
    views: "2.1M views",
    duration: "25:40",
    description: "Full review of the hottest new game release. Is it worth your money?",
    channelSubscribers: "3M subscribers",
    uploadDate: "3 days ago",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
  },
  "g2": {
    id: "g2",
    title: "Epic Gaming Moments Compilation",
    channel: "Game Clips",
    views: "3.5M views",
    duration: "18:22",
    description: "The most epic gaming moments from this month. You won't believe #7!",
    channelSubscribers: "4.5M subscribers",
    uploadDate: "1 week ago",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4",
  },
  "g3": {
    id: "g3",
    title: "Speedrun World Record",
    channel: "Speed Gamers",
    views: "1.9M views",
    duration: "32:15",
    description: "Watch as this player breaks the world record speedrun for this classic game.",
    channelSubscribers: "2.5M subscribers",
    uploadDate: "4 days ago",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
  },
  "e1": {
    id: "e1",
    title: "Computer Science Fundamentals",
    channel: "Edu Tech",
    views: "980K views",
    duration: "45:30",
    description: "Master the fundamental concepts of computer science in this comprehensive lecture.",
    channelSubscribers: "1.5M subscribers",
    uploadDate: "2 weeks ago",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
  },
  "e2": {
    id: "e2",
    title: "Data Structures Explained",
    channel: "Learn Code",
    views: "1.5M views",
    duration: "35:20",
    description: "Understanding data structures made simple. Learn the essentials for coding interviews.",
    channelSubscribers: "2.2M subscribers",
    uploadDate: "1 week ago",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
  },
  "e3": {
    id: "e3",
    title: "Algorithms Made Simple",
    channel: "Code School",
    views: "1.2M views",
    duration: "28:15",
    description: "Simplifying complex algorithms so anyone can understand them.",
    channelSubscribers: "1.8M subscribers",
    uploadDate: "5 days ago",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
  },
};

export const getVideoDetails = (videoId) => {
  if (!videoId || !videoDetailsMap[videoId]) {
    // Default video
    return {
      id: "default",
      title: "Complete Guide to Modern Web Development",
      channel: "Tech Master Channel",
      views: "1.2M views",
      duration: "45:30",
      description: "Master modern web development with this comprehensive guide covering React, TypeScript, and more.",
      channelSubscribers: "2.5M subscribers",
      uploadDate: "1 week ago",
      videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    };
  }
  return videoDetailsMap[videoId];
};
